# Generated by Django 2.2.5 on 2019-09-22 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=120)),
                ('quantidade_em_estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_minimo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
